export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';



export const ADD_STICKER_TO_BUNDLE = 'ADD_STICKER_TO_BUNDLE';
export const REMOVE_STICKER_FROM_BUNDLE = 'REMOVE_STICKER_FROM_BUNDLE';
export const SET_STICKER_STATE='SET_STICKER_STATE';
export const SET_STICKERS='SET_STICKERS';
export const ADD_STICKER_TO_STORE='ADD_STICKER_TO_STORE';
export const UPDATE_STICKER_IN_STORE='UPDATE_STICKER_IN_STORE';


export const SET_COUNTRIES = 'SET_COUNTRIES';
export const SET_GRAPES = 'SET_GRAPES';
export const SET_REGIONS = 'SET_REGIONS';
export const SET_APPELLATIONS = 'SET_APPELLATIONS';
export const SET_PRODUCERS = 'SET_PRODUCERS';
export const SET_LOADING='SET_LOADING';

